#
# Ubuntu saucy box (13.10) with default options.
#

Vagrant::Config.run do |config|
  config.vm.box = 'saucy64'
  config.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.network :hostonly, "192.168.33.10"
  config.ssh.forward_agent = true
 
  # https://github.com/mitchellh/vagrant/issues/1172
  config.vm.share_folder "vagrant-root", "/vagrant", ".", nfs:
    RUBY_PLATFORM =~ /darwin/ || RUBY_PLATFORM =~ /linux/

end