
Vagrant.configure('2') do |config|
  nodes.each do |node|
 
    config.vm.provider "virtualbox" do |vb|
      vb.customize ['modifyvm', :id, '--memory', node[:mem]]
      vb.customize ['modifyvm', :id, '--cpus', node[:cpus]]
 
      # do not change
      vb.customize ['modifyvm', :id, '--hwvirtex', 'on']
    end
 
    config.vm.define node[:hostname], primary: true do |instance|
      instance.vm.box = node[:box]
      instance.vm.box_url = node[:url]
      instance.vm.host_name = node[:hostname]# + '.' + domain
      instance.vm.network 'private_network', ip: node[:ip]
    end # end define
  end # end nodes
end