## Vagrantfile

upgrade = <<SCRIPT
echo Running apt-get update and upgrade...
sudo apt-get update -y
sudo apt-get upgrade -y
SCRIPT

installs = <<SCRIPT
sudo apt-get install -y vim git
SCRIPT

#Vagrant.require_plugin 'vagrant-vbguest'
#Vagrant.require_plugin 'vagrant-berkshelf'
#Vagrant.require_plugin 'vagrant-omnibus'

Vagrant.configure("2") do |config|

  # Base setup
  config.vm.box = 'holobot-dev-v3'
  #config.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box'
  config.vm.box_url = '../base-boxes/coreos_production_vagrant.box'
  #config.vm.box_url = '../base-boxes/raring-server-cloudimg-amd64-vagrant-disk1.box'

  # Vbox specific configs, should think about removing these
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"] #in case it is needed
    vb.customize ["modifyvm", :id, "--pae", "on"] #in case it is needed
    vb.customize ["modifyvm", :id, "--memory", "512"] #min ram to build box
    vb.customize ["modifyvm", :id, "--cpus", "1"] #making sure cpus are accounted at min
    vb.gui = true #just in case
  end

  # Network
  config.vm.network :public_network, :bridge => 'en0: Wi-Fi (AirPort)'
  # config.vm.network :private_network, ip: "10.10.10.10"
  # config.ssh.username = 'core'
  # config.ssh.forward_agent = true
  # config.ssh.timeout = 500
  # config.ssh.max_tries = 40

  # disable shared folder
  # config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

  # installs
  #config.vm.provision :shell, inline: upgrade
  #config.vm.provision :shell, inline: installs

  # berkshelf - if we want to utilize
  # config.berkshelf.enabled = true

  # chef
  #
  #end

end