Vagrant.configure("2") do |config|
  config.vm.box = 'holobot-dev'
  config.vm.box_url = '/Volumes/Storage for Jason/ISOs/saucy-server-cloudimg-amd64-vagrant-disk1.box'
  #config.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box'

  config.vm.provider :virtualbox do |vb|
    #vb.customize ["modifyvm", :id, "--hwvirtex", "off"] #in case it is needed
    #vb.customize ["modifyvm", :id, "--cpus", "1"] #making sure cpus are accounted at min
    #vb.gui = true #just in case
  end

  config.vm.network :private_network, ip: "10.10.10.10"
  config.ssh.forward_agent = true
  config.ssh.timeout = 300

  # disable shared folder
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

end

