# -*- mode: ruby -*-
# vi: set ft=ruby :

site :opscode


# -- ENV --
cookbook 'apt'
cookbook 'build-essential'


# -- TOOLING --
cookbook 'git'
# cookbook 'ruby_build'
# cookbook 'nvm', git: 'https://github.com/jmreidy/chef-nvm', :ref => 'master'
# cookbook 'zsh'
cookbook 'vim'
# cookbook 'tmux'
# cookbook 'the_silver_searcher'


# Testing
cookbook 'phantomjs'


# datastores 
#cookbook 'postgres'
#cookbook 'mongodb'
#cookbook 'redisio'