source "https://rubygems.org"

gem 'foodcritic'

gem 'berkshelf', '~> 2.0.7'
gem 'test-kitchen', '~> 1.0.0.alpha'
gem 'kitchen-vagrant', '~> 0.10.0'
# gem 'veewee' # looks to have a dependency issue?

